name: Deploy xray for server
on: 
  workflow_dispatch:
    inputs:
      domain:
        description: 'add domain'     
        required: true
        default: fq.imrcrab.com
      startport:
        description: 'start port'     
        required: true
        default: '1451'
      endport:
        description: 'end port'     
        required: true
        default: '1460'
env:
  XRAY_VERSION: v1.6.6-2
  XRAY_DIR: xray

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d%H%M')"
        shell: bash
      - name: Reponse body
        id: response_info_1
        run: |
          cd ${{ env.XRAY_DIR }}
          ls -all
          ls -all
          result=$(ls |wc -l)
          rs='false'
          echo $result"................."
          if [[ result -gt 0 ]];then
            rs='true'
          fi
          echo "::set-output name=run_project_b_build::${rs}"

      - name: Build project
        if: ${{ steps.response_info_1.outputs.run_project_b_build == 'true' }}
        run: |
          cd ${{ env.XRAY_DIR }}
          wget -v https://github.com/XTLS/Xray-core/releases/download/${{ env.XRAY_VERSION }}/Xray-linux-64.zip
          cd ../
          pwd
          ls -all ${{ env.XRAY_DIR }}/
      - name: copy file via ssh key
        if: ${{ steps.response_info_1.outputs.run_project_b_build == 'true' }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY }}
          source: "./${{ env.XRAY_DIR }}"
          target: "/root"
      - name: mv ./xray to outside
        if: ${{ steps.response_info_1.outputs.run_project_b_build == 'true' }}
        uses: appleboy/ssh-action@master
        with:
          overwrite: true
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /root/${{ env.XRAY_DIR }}
            chmod +x xray_template_install.sh
            ./xray_template_install.sh ${{ github.event.inputs.domain }} ${{ github.event.inputs.startport }} ${{ github.event.inputs.endport }}
            
      - name: git push change file
        if: ${{ steps.response_info_1.outputs.run_project_b_build == 'true' }}
        continue-on-error: true
        run: |
          git config --local user.name "crab"
          git config --local user.email "imrcrab@163.com"
          git add ${{ env.XRAY_DIR }}/version.yml
          git commit -m "modify: auto by action"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/crab21/vps_deploy.git
          rm -rf ~/.ssh
